package config

// SiteShortName bla bla...
const SiteShortName string = "GoWebApp"

// SiteFullName bla bla...
const SiteFullName string = "Maharlikans Code"

// SiteSlogan bla bla...
const SiteSlogan string = "Hello Maharlikans, Welcome to our Web Development Series"

// SiteYear bla bla...
const SiteYear int = 2021

//SiteRootTemplate bla bla...
const SiteRootTemplate string = "html/"

//SiteDomainName bla bla...
const SiteDomainName string = "maharlikanscode.com"

//SiteProperDomainName bla bla...
const SiteProperDomainName string = "MaharlikansCode.com"

//SiteHeaderTemplate bla bla...
const SiteHeaderTemplate = SiteRootTemplate + "layout/header_front.html"

//SiteHeaderAccountTemplate bla bla...
const SiteHeaderAccountTemplate = SiteRootTemplate + "layout/header_account.html"

//SiteHeaderDashTemplate bla bla...
const SiteHeaderDashTemplate = SiteRootTemplate + "layout/header_dash.html"

//SiteFooterTemplate bla bla...
const SiteFooterTemplate = SiteRootTemplate + "layout/footer_front.html"

//SiteFooterAccountTemplate bla bla...
const SiteFooterAccountTemplate = SiteRootTemplate + "layout/footer_account.html"

//SiteFooterDashTemplate bla bla...
const SiteFooterDashTemplate = SiteRootTemplate + "layout/footer_dash.html"

//SiteBaseURL bla bla...
const SiteBaseURL = "http://localhost:4000/"

//SiteTopMenuLogo bla bla...
const SiteTopMenuLogo = "/static/assets/images/maharlikanscode_top_logo.png"

//EmailLogo bla bla...
const EmailLogo = SiteBaseURL + "static/assets/images/maharlikanscode_top_logo.png"

//SiteEmail bla bla...
const SiteEmail = "support@maharlikanscode.com"

//SitePhoneNumbers bla bla...
const SitePhoneNumbers = ""

//SiteCompanyAddress bla bla...
const SiteCompanyAddress = "Your company address here"

//SiteTimeZone bla bla...
const SiteTimeZone = "Asia/Manila"

//SecretKeyCORS bla bla...
const SecretKeyCORS = "n&@ix77r#^&^cgeb13w@!+pht^6qu-=("

//MyEncryptDecryptSK bla bla...
const MyEncryptDecryptSK = "mkc&1*~#^8^#s0^=)^^7%a12"
